### PR TITLE
Added some modules to support openrouter

### PR DESCRIPTION
**Pull request by renlifei1994**
仿照原有的接入one-api/vllm/ollama的内容，增加了一些关于支持openrouter的模块。
界面如下：
image
image

### CODE REVIEW

**Comment by binary-husky** [comment]
thank you, we will look into it and merge to `frontier` branch first

**Comment by binary-husky** [comment]
image

This regex  seems strange. what does their keys looks like?

**Comment by binary-husky** [comment]
I have made some changes to simplify some of the unused functions, can you help me verify the version? 
Thank you!

**Comment by renlifei1994** [comment]
> image
> 
> This regex seems strange. what does their keys looks like?

I have generate three keys of openrouter, and they are listed as follows:
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
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
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
So we need changes the regex because the number of digits for different the keys is not fixed. The regex I used in previous version is only applicable to my keys.
In addition, the prefix is also strange because it contains "v1". May be it will includes "v2" for different users or in future ？ Would you please help to generate different keys, and modify the regex according the results ? Many thanks.

**Review by renlifei1994 — COMMENTED** [review]
Many thanks. I have reviewed the modified code, and it is more clear and elegant after your revision. Thanks.

**Pull request merged**
